version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - archnet

  itemservice:
    container_name: itemservice
    build:
      context: ./ItemService
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    networks:
      - archnet
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  sampleservice:
    container_name: sampleservice
    build: 
      context: ./SampleService
      dockerfile: Dockerfile
    ports:
      - 5006:5006
    networks:
      - archnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mongodbdata:

networks:
  archnet:
    driver: bridge